# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "09585d83a6e6bdfb212dc6265530bf64"
application_url = "https://stuff-responses-mistake-consoles.trycloudflare.com"
embedded = true
name = "b2b"
handle = "b2b-31"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://stuff-responses-mistake-consoles.trycloudflare.com/auth/callback",
  "https://stuff-responses-mistake-consoles.trycloudflare.com/auth/shopify/callback",
  "https://stuff-responses-mistake-consoles.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "octspace-b2b.myshopify.com"
automatically_update_urls_on_dev = true
